// Public surface as of main on 2026-09-12. When intentionally making an export private,
// remove it here too; otherwise this test must fail.
import { describe, expect, it } from 'vitest'

import {
  __getDeviceSwitchBridgeForTest,
  __getEngineProcessForTest,
  __getPlayheadActiveRangeCountForTest,
  __getPlayheadTimeoutCountForTest,
  __getPluginUiBridgeForTest,
  __pluginUiForAgentForTest,
  __resetPlayheadStateForTest,
  __setEngineProcessForTest,
  __setEngineViewProviderForTest,
  __setLiveCodingModeForTest,
  __setOutputChannelForTest,
  __setPlayheadActiveRangeForTest,
  __setStatusBarItemForTest,
  activate,
  createLinePrefixer,
  deactivate,
  dslCompletionItemProvider,
  registerCompletionProviders,
  registerOutputCodeActionProvider,
  setupErrorHandler,
  setupExitHandler,
  setupStderrHandler,
  setupStdinErrorHandler,
  setupStdoutHandler,
  startEngineForAgent,
  stopEngine,
  toggleEngine,
} from '../../packages/vscode-extension/src/extension'
import {
  DOCS_PUBLIC_BASE,
  USER_DOCS_PUBLIC_BASE,
  isDocsDistStale,
  matchDocsRequest,
  readDevDoc,
  resolveDocsFilePath,
  resolveDocsRoot,
  resolveMcpPluginUiIndex,
  resolveUserDocsRoot,
  searchDevDocs,
  startOrbitScoreMcpServer,
} from '../../packages/vscode-extension/src/mcp-server'
import type {
  AnalyzeAudioResult,
  AudioDeviceInfo,
  AudioDevicesResult,
  CommandResult,
  DevDocSearchMatch,
  DiagnosticEntry,
  DiagnosticSeverityLabel,
  DocumentText,
  EditorState,
  EngineState,
  EvaluateResult,
  FileDiagnostics,
  FlashConfig,
  FlashConfigInput,
  FlashConfigResult,
  ListPluginsResult,
  McpServerHandle,
  OrbitScoreToolHandlers,
  PluginCatalogEntryInfo,
  PluginUiResult,
  RegisterMcpServerInput,
  RescanPluginsResult,
  SavePluginStateResult,
  SelectionInput,
  EditReplaceInput,
} from '../../packages/vscode-extension/src/mcp-server'

export type McpTypeSurface = [
  AnalyzeAudioResult,
  AudioDeviceInfo,
  AudioDevicesResult,
  CommandResult,
  DevDocSearchMatch,
  DiagnosticEntry,
  DiagnosticSeverityLabel,
  DocumentText,
  EditorState,
  EngineState,
  EvaluateResult,
  FileDiagnostics,
  FlashConfig,
  FlashConfigInput,
  FlashConfigResult,
  ListPluginsResult,
  McpServerHandle,
  OrbitScoreToolHandlers,
  PluginCatalogEntryInfo,
  PluginUiResult,
  RegisterMcpServerInput,
  RescanPluginsResult,
  SavePluginStateResult,
  SelectionInput,
  EditReplaceInput,
]

const surface = {
  __getDeviceSwitchBridgeForTest,
  __getEngineProcessForTest,
  __getPlayheadActiveRangeCountForTest,
  __getPlayheadTimeoutCountForTest,
  __getPluginUiBridgeForTest,
  __pluginUiForAgentForTest,
  __resetPlayheadStateForTest,
  __setEngineProcessForTest,
  __setEngineViewProviderForTest,
  __setLiveCodingModeForTest,
  __setOutputChannelForTest,
  __setPlayheadActiveRangeForTest,
  __setStatusBarItemForTest,
  activate,
  createLinePrefixer,
  deactivate,
  dslCompletionItemProvider,
  registerCompletionProviders,
  registerOutputCodeActionProvider,
  setupErrorHandler,
  setupExitHandler,
  setupStderrHandler,
  setupStdinErrorHandler,
  setupStdoutHandler,
  startEngineForAgent,
  stopEngine,
  toggleEngine,
  DOCS_PUBLIC_BASE,
  USER_DOCS_PUBLIC_BASE,
  isDocsDistStale,
  matchDocsRequest,
  readDevDoc,
  resolveDocsFilePath,
  resolveDocsRoot,
  resolveMcpPluginUiIndex,
  resolveUserDocsRoot,
  searchDevDocs,
  startOrbitScoreMcpServer,
}

describe('public surface of extension.ts / mcp-server.ts', () => {
  it.each(Object.entries(surface))('%s is a value at runtime', (_name, value) => {
    expect(value).toBeDefined()
  })
})
