name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  claude-review:
    # Only run if not a release PR (develop -> main)
    if: github.event.pull_request.base.ref != 'main'

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read
      checks: write
      id-token: write

    steps:
      - name: Wait for CI/CD to complete
        id: check-ci
        uses: actions/github-script@v7
        with:
          script: |
            const maxAttempts = 60; // 10 minutes max (10 seconds * 60)
            const delay = 10000; // 10 seconds

            for (let attempt = 0; attempt < maxAttempts; attempt++) {
              const { data: checkRuns } = await github.rest.checks.listForRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: context.payload.pull_request.head.sha,
              });

              const ciCheck = checkRuns.check_runs.find(run =>
                run.name === 'code-review' &&
                run.app.slug === 'github-actions'
              );

              if (ciCheck) {
                if (ciCheck.status === 'completed') {
                  if (ciCheck.conclusion === 'success') {
                    core.info('✅ CI/CD check passed');
                    return;
                  } else {
                    core.setFailed(`CI/CD check failed with conclusion: ${ciCheck.conclusion}`);
                    return;
                  }
                }
                core.info(`⏳ CI/CD check status: ${ciCheck.status}, waiting...`);
              } else {
                core.info('⏳ CI/CD check not found yet, waiting...');
              }

              await new Promise(resolve => setTimeout(resolve, delay));
            }

            core.setFailed('Timeout waiting for CI/CD check (10 minutes)');

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}

            **重要: レビューは必ず日本語で記述してください。**

            このプルリクエストをレビューし、以下の観点からフィードバックを提供してください：
            - コード品質とベストプラクティス
            - 潜在的なバグや問題
            - パフォーマンスに関する考慮事項
            - セキュリティの懸念
            - テストカバレッジ

            リポジトリのCLAUDE.mdを参照し、スタイルと規約に関するガイダンスに従ってください。建設的で役立つフィードバックを心がけてください。

            `gh pr comment`コマンドとBashツールを使用して、PRにレビューコメントを投稿してください。レビューコメントは日本語で記述してください。

          # See https://github.com/anthropics/claude-code-action/blob/main/docs/usage.md
          # or https://docs.claude.com/en/docs/claude-code/cli-reference for available options
          claude_args: '--allowed-tools "Bash(gh issue view:*),Bash(gh search:*),Bash(gh issue list:*),Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr list:*)"'

